apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storage.className }}
  labels:
    {{- include "ephemeral-disk-storage.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
provisioner: containerstorage.csi.azure.com
parameters:
  pool: ephemeraldisk
volumeBindingMode: {{ .Values.storage.volumeBindingMode }}
allowVolumeExpansion: {{ .Values.storage.allowVolumeExpansion }}
