apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "aznhc.fullname" . }}
spec:
  parallelism: {{ .Values.nodes }}
  completions: {{ .Values.nodes }}
  template:
    metadata:
      labels:
        app: aznhc
        task: {{ include "aznhc.fullname" . }}
{{- if .Values.kueue.queueName }}
        kueue.x-k8s.io/queue-name: {{ .Values.kueue.queueName }}
{{- end }}
    spec:
      restartPolicy: Never
      containers:
      - name: aznhc
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          capabilities:
            add: ["IPC_LOCK"]
        resources:
          requests:
            {{ .Values.gpuResource }}: {{ .Values.gpusPerNode }}
            {{ .Values.rdmaResource }}: {{ .Values.gpusPerNode }}
          limits:
            {{ .Values.gpuResource }}: {{ .Values.gpusPerNode }}
            {{ .Values.rdmaResource }}: {{ .Values.gpusPerNode }}
        volumeMounts:
        - mountPath: /dev/shm
          name: shmem
        - mountPath: /azure-nhc/syslog
          name: syslog-volume
          readOnly: true
        - mountPath: /var/lib/hyperv/.kvp_pool_3
          name: kvp-pool-volume
          readOnly: true
        command:
        - /bin/bash
        - -c
        - |
          cat <<EOF > /azure-nhc/aznhc.conf
{{ .Values.nhcConfig | indent 10 }}
          EOF
          /azure-nhc/aznhc_entrypoint.sh
      volumes:
      - name: shmem
        emptyDir:
          medium: Memory
          sizeLimit: 128Gi
      - name: syslog-volume
        hostPath:
          path: /var/log/syslog
          type: File
      - name: kvp-pool-volume
        hostPath:
          path: /var/lib/hyperv/.kvp_pool_3
          type: File

