apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  name: {{ .Values.localQueue.name }}
  namespace: {{ .Values.localQueue.namespace }}
spec:
  clusterQueue: {{ .Values.clusterQueue.name }}
