{{- if eq .Values.storage.type "blobfuse" }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "fio.fullname" . }}-blob-storage
  labels:
    {{- include "fio.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
mountOptions:
  {{- range .Values.storage.blobfuse.mountOptions }}
  - {{ . | quote }}
  {{- end }}
parameters:
  skuName: {{ .Values.storage.blobfuse.skuName }}
provisioner: blob.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
{{- else if eq .Values.storage.type "azure-container-storage" }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "fio.fullname" . }}-acstor
  labels:
    {{- include "fio.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
provisioner: containerstorage.csi.azure.com
parameters:
  pool: ephemeraldisk
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false
{{- else if eq .Values.storage.type "localpv" }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "fio.fullname" . }}-local
  labels:
    {{- include "fio.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
{{- end }}
